from __future__ import annotations

from ssrn_monitor.models import WatchTarget
from ssrn_monitor.normalize import normalize_text, tokenize_for_overlap


RAW_WATCH_TARGETS: tuple[tuple[int, int, str, str, str], ...] = (
    (1, 1, "Duke University", "Xu Jiang", "The Fuqua School of Business"),
    (2, 2, "University of Pennsylvania", "Frank S Zhou", "The Wharton School"),
    (3, 3, "University of Navarra", "Gaizka Ormazabal", "IESE Business School"),
    (4, 4, "University of North Carolina at Chapel Hill", "Stephen Glaeser", "Kenan-Flagler Business School"),
    (5, 5, "University of Pennsylvania", "Christina Zhu", "The Wharton School"),
    (6, 6, "Pennsylvania State University at State College (Penn State)", "Daniel Aobdia", "Smeal College of Business"),
    (7, 7, "Yale University", "Edward M Watts", "School of Management"),
    (8, 8, "University of Minnesota at Twin Cities", "Gaoqing Zhang", "Carlson School of Management"),
    (9, 9, "University of London", "Marcel Olbert", "London Business School"),
    (10, 10, "University of Pennsylvania", "Matthew J Bloomfield", "The Wharton School"),
    (11, 11, "University of California at Berkeley", "Omri Even-Tov", "Walter A. Haas School of Business"),
    (12, 12, "Columbia University", "Thomas Bourveau", "Columbia Business School"),
    (13, 13, "University of Texas at Austin", "Volker Laux", "McCombs School of Business"),
    (14, 14, "Washington University in St. Louis", "Xiumin Martin", "Olin School of Business"),
    (15, 15, "New York University (NYU)", "Yiwei Dou", "Leonard N Stern School of Business"),
    (16, 16, "Boston College", "Benjamin P Yost", "Carroll School of Management"),
    (17, 17, "Stanford University", "Brandon Gipper", "Graduate School of Business"),
    (18, 18, "University of Chicago", "Charles G McClure", "Booth School of Business"),
    (19, 19, "Stanford University", "Charles M C Lee", "Graduate School of Business"),
    (20, 20, "University of Southern California", "Clive Lennox", "Marshall School of Business (incl. Leventhal)"),
    (21, 21, "Centre for Economic Policy Research (CEPR)", "Gaizka Ormazabal", ""),
    (22, 22, "European Corporate Governance Institute (ECGI)", "Gaizka Ormazabal", ""),
    (23, 23, "Washington University in St. Louis", "Jeremy Bertomeu", "Olin School of Business"),
    (24, 24, "Stanford University", "Jinhwan Kim", "Graduate School of Business"),
    (25, 25, "Stanford University", "John D Kepler", "Graduate School of Business"),
    (26, 26, "Harvard University", "Jonas Heese", "Harvard Business School"),
    (27, 27, "Harvard University", "Joseph Pacelli", "Harvard Business School"),
    (28, 28, "Stanford University", "Jung Ho Choi", "Graduate School of Business"),
    (29, 29, "Rice University", "Karthik Balakrishnan", "Jesse H. Jones Graduate School of Business"),
    (30, 30, "Emory University", "Kathryn Kadous", "Goizueta Business School"),
    (31, 31, "University of Georgia", "Kristen Valentine", "Terry College of Business"),
    (32, 32, "University of Navarra", "Martin Jacob", "IESE Business School"),
    (33, 33, "University of Texas at Austin", "Matthew Kubic", "McCombs School of Business"),
    (34, 34, "Columbia University", "Matthias Breuer", "Columbia Business School"),
    (35, 35, "Massachusetts Institute of Technology (MIT)", "Michelle Hanlon", "Sloan School of Management"),
    (36, 36, "INSEAD", "Oliver Binz", "School of Business"),
    (37, 37, "Stanford University", "Rebecca Lester", "Graduate School of Business"),
    (38, 38, "University of Southern California", "Richard G Sloan", "Marshall School of Business (incl. Leventhal)"),
    (39, 39, "University of Texas at Austin", "Ronghuo Zheng", "McCombs School of Business"),
    (40, 40, "Texas A&M University at College Station", "Sarah B Stuber", "Mays Business School"),
    (41, 41, "University of California at Irvine", "Terry Shevlin", "Paul Merage School of Business"),
    (42, 42, "Northeastern University", "Udi Hoitash", "D'Amore-McKim School of Business"),
    (43, 43, "University of Florida", "W Robert Knechel", "Warrington College of Business"),
    (44, 44, "University of North Carolina at Chapel Hill", "Wayne R Landsman", "Kenan-Flagler Business School"),
    (45, 45, "Ohio State University", "Anil Arya", "Fisher College of Business"),
    (46, 46, "University of Utah", "Atif Ellahie", "David Eccles School of Business"),
    (47, 47, "University of Kentucky", "Benjamin P Commerford", "Gatton College of Business and Economics"),
    (48, 48, "New York University (NYU)", "Christine Cuny", "Leonard N Stern School of Business"),
    (49, 49, "Stanford University", "Christoher S. Armstrong", "Graduate School of Business"),
    (50, 50, "University of Minnesota at Twin Cities", "Cyrus Aghamolla", "Carlson School of Management"),
    (51, 51, "University of Iowa", "Dain C Donelson", "Henry B. Tippie College of Business"),
    (52, 52, "University of Chicago", "Delphine Samuels", "Booth School of Business"),
    (53, 53, "Stanford University", "Ed deHaan", "Graduate School of Business"),
    (54, 54, "Duke University", "Elia Ferracuti", "The Fuqua School of Business"),
    (55, 55, "Indiana University at Bloomington", "Eric R Holzman", "Kelley School of Business"),
    (56, 56, "University of Texas at Austin", "Eric W Chan", "McCombs School of Business"),
    (57, 57, "University of North Carolina at Chapel Hill", "Eva Labro", "Kenan-Flagler Business School"),
    (58, 58, "University of Mannheim", "Felix W Vetter", "Business School"),
    (59, 59, "University of Hong Kong", "Guoman She", "Faculty of Business and Economics / HKU Business School)"),
    (60, 60, "Tulane University", "Gus De Franco", "A. B. Freeman School of Business"),
    (61, 61, "University of Michigan at Ann Arbor", "Gwen Yu", "Ross School of Business"),
    (62, 62, "University of Chicago", "Haresh Sapra", "Booth School of Business"),
    (63, 63, "University of Iowa", "Jaron H Wilde", "Henry B. Tippie College of Business"),
    (64, 64, "Pennsylvania State University at State College (Penn State)", "Jed J Neilson", "Smeal College of Business"),
    (65, 65, "University of North Carolina at Chapel Hill", "Jeffrey L. Hoopes", "Kenan-Flagler Business School"),
    (66, 66, "University of Texas at Austin", "John McInnis", "McCombs School of Business"),
    (67, 67, "Duke University", "Katherine Schipper", "The Fuqua School of Business"),
    (68, 68, "Stanford University", "Kevin C Smith", "Graduate School of Business"),
    (69, 69, "University of Texas at Austin", "Lisa De Simone", "McCombs School of Business"),
    (70, 70, "Tilburg University", "Lucas Mahieux", "(TiSEM) School of Economics and Management (incl. Econometrics and Operations Research depts.)"),
    (71, 71, "Cornell University", "Luo Zuo", "SC Johnson College of Business, Johnson Graduate School of Management (Incl. Dyson and Nolan)"),
    (72, 72, "University of Hong Kong", "Lynn Linghuan Wang", "Faculty of Business and Economics / HKU Business School)"),
    (73, 73, "WHU", "Martin Jacob", "Otto Beisheim School of Management - School of Management"),
    (74, 74, "Boston College", "Mary Ellen Carter", "Carroll School of Management"),
    (75, 75, "University at Buffalo / State University of New York (SUNY) at Buffalo", "Michael Dambra", "School of Management"),
    (76, 76, "Duke University", "Mohan Venkatachalam", "The Fuqua School of Business"),
    (77, 77, "Massachusetts Institute of Technology (MIT)", "Nemit Shroff", "Sloan School of Management"),
    (78, 78, "University of Texas at Dallas", "Ningzhong Li", "Naveen Jindal School of Management"),
    (79, 79, "University of Iowa", "Paul Hribar", "Henry B. Tippie College of Business"),
    (80, 80, "University of Utah", "Rachel M Hayes", "David Eccles School of Business"),
    (81, 81, "University of Southern California", "Regina Wittenberg-Moerman", "Marshall School of Business (incl. Leventhal)"),
    (82, 82, "University of Chicago", "Rimmy E Tomy", "Booth School of Business"),
    (83, 83, "Cornell University", "Robert J Bloomfield", "SC Johnson College of Business, Johnson Graduate School of Management (Incl. Dyson and Nolan)"),
    (84, 84, "Massachusetts Institute of Technology (MIT)", "Rodrigo S Verdi", "Sloan School of Management"),
    (85, 85, "New York University (NYU)", "Stephen G Ryan", "Leonard N Stern School of Business"),
    (86, 86, "Temple University", "Sudipta Basu", "The Fox School of Business and Management"),
    (87, 87, "University of Auckland", "W Robert Knechel", "The University of Auckland Business School"),
    (88, 88, "National University of Singapore (NUS)", "Yupeng Lin", "NUS Business School"),
    (89, 89, "University of Colorado at Boulder", "A Nicole Skinner", "Leeds School of Business"),
    (90, 90, "University of Georgia", "A Nicole Skinner", "Terry College of Business"),
    (91, 91, "Northwestern University", "Aaron Yoon", "Kellogg School of Management"),
    (92, 92, "Hong Kong University of Science and Technology (HKUST)", "Allen H Huang", "Business School"),
    (93, 93, "University of Pennsylvania", "Allison Nicoletti", "The Wharton School"),
    (94, 94, "Singapore Management University", "An-Ping Lin", "Lee Kong Chian School of Business"),
    (95, 95, "University of Colorado at Boulder", "Andrea Pawliczek", "Leeds School of Business"),
    (96, 96, "University of Texas at Austin", "Andrew Belnap", "McCombs School of Business"),
    (97, 97, "Massachusetts Institute of Technology (MIT)", "Andrew G Sutherland", "Sloan School of Management"),
    (98, 98, "Ohio State University", "Andrew Van Buskirk", "Fisher College of Business"),
    (99, 99, "Yale University", "Aneesh Raghunandan", "School of Management"),
    (100, 100, "Stanford University", "Anne Beyer", "Graduate School of Business"),
    (101, 101, "University of Illinois at Urbana-Champaign", "Anne M Thompson", "Gies College of Business"),
    (102, 102, "Bocconi University / Universita Bocconi", "Antonio Marra", "SDA School of Management"),
    (103, 103, "Yale University", "Anya Nakhmurina", "School of Management"),
    (104, 104, "University of London", "Aytekin Ertan", "London Business School"),
    (105, 105, "Seoul National University (SNU)", "Bok Baik", "College of Business Administration / Business School"),
    (106, 106, "Texas A&M University at College Station", "Bradford F Hepfer", "Mays Business School"),
    (107, 107, "University of North Carolina at Chapel Hill", "Bradley E Hendricks", "Kenan-Flagler Business School"),
    (108, 108, "University of Utah", "Brian Cadman", "David Eccles School of Business"),
    (109, 109, "Indiana University at Bloomington", "Brian M Williams", "Kelley School of Business"),
    (110, 110, "University of Colorado at Boulder", "Bryce Schonberger", "Leeds School of Business"),
    (111, 111, "Hong Kong University of Science and Technology (HKUST)", "Chao Tang", "Business School"),
    (112, 112, "Monash University", "Chen Chen", "Monash Business School"),
    (113, 113, "Ludwig Maximilian University of Munich (LMU) (Munich University)", "Christian Hofmann", "Faculty of Business Administration - Munich School of Management, Munich Business School"),
    (114, 114, "University of Chicago", "Christian Leuz", "Booth School of Business"),
    (115, 115, "WU Vienna University of Economics and Business / Wirtschafts Universitat Wien", "Christoph Feichter", "Vienna University of Economics and Business"),
    (116, 116, "University of Oregon", "Dane M Christensen", "Charles H. Lundquist College of Business"),
    (117, 117, "University of Miami", "Daniele Macciocchi", "School of Business Administration / Herbert Business School"),
    (118, 118, "Stanford University", "David F Larcker", "Graduate School of Business"),
    (119, 119, "New Economic School", "Davide Cianciaruso", ""),
    (120, 120, "City University of New York, Baruch College", "Edward Xuejun Li", "Zicklin School of Business"),
    (121, 121, "Colorado State University, Ft. Collins", "Elizabeth N Cowle", "College of Business"),
    (122, 122, "Temple University", "Enrique A Gomez", "The Fox School of Business and Management"),
    (123, 123, "Carnegie Mellon University", "Gaoqing Zhang", "Tepper School of Business"),
    (124, 124, "University of California at San Diego", "Gerardo Perez-Cavazos", "Rady School of Management"),
    (125, 125, "University of Iowa", "H Scott Asay", "Henry B. Tippie College of Business"),
    (126, 126, "University of Chicago", "Hans B Christensen", "Booth School of Business"),
    (127, 127, "Duke University", "Hao Xue", "The Fuqua School of Business"),
    (128, 128, "University of California at Los Angeles", "Henry L Friedman", "Anderson School of Management"),
    (129, 129, "Purdue University", "Hojun Seo", "Mitchell E. Daniels, Jr. School of Business / Krannert School of Management"),
    (130, 130, "Tilburg University", "Jacob Zureich", "(TiSEM) School of Economics and Management (incl. Econometrics and Operations Research depts.)"),
    (131, 131, "University of Oregon", "Jaewoo Kim", "Charles H. Lundquist College of Business"),
    (132, 132, "University of Michigan at Ann Arbor", "James D Omartian", "Ross School of Business"),
    (133, 133, "Texas A&M University at College Station", "James D Warren", "Mays Business School"),
    (134, 134, "University of Virginia, McIntire", "Jasmine Wang", "McIntire School of Commerce"),
    (135, 135, "University of Illinois at Chicago", "Jason V Chen", "College of Business Administration"),
    (136, 136, "University of Toronto", "Jee-Eun Shin", "Joseph L. Rotman School of Management"),
    (137, 137, "Memorial University of Newfoundland", "Jeffrey A Pittman", "Faculty of Business Administration"),
    (138, 138, "City University of Hong Kong", "Jeong-Bon Kim", "College of Business"),
    (139, 139, "University of Massachusetts at Amherst", "Jeremiah W Bentley", "Eugene M.Isenberg School of Management"),
    (140, 140, "University of Rochester", "Joanna Shuang Wu", "Simon Business School"),
    (141, 141, "University of Notre Dame", "John Donovan", "Mendoza College of Business"),
    (142, 142, "University of Georgia", "John L Campbell", "Terry College of Business"),
    (143, 143, "Texas A&M University at College Station", "John R Robinson", "Mays Business School"),
    (144, 144, "Brigham Young University", "Joshua A Lee", "Marriott School of Management"),
    (145, 145, "Harvard University", "Jung Koo Kang", "Harvard Business School"),
    (146, 146, "University of Illinois at Urbana-Champaign", "Justin Leiby", "Gies College of Business"),
    (147, 147, "University of Florida", "K Philip Wang", "Warrington College of Business"),
    (148, 148, "Rice University", "K Ramesh", "Jesse H. Jones Graduate School of Business"),
    (149, 149, "Georgia Institute of Technology", "Kathy Rupar", "Scheller College of Business"),
    (150, 150, "McMaster University", "Ken Li", "DeGroote School of Business"),
    (151, 151, "Indiana University at Bloomington", "Kenneth Merkley", "Kelley School of Business"),
    (152, 152, "National Taiwan University", "Kevin Tseng", "College of Management"),
    (153, 153, "The Chinese University of Hong Kong (CUHK)", "Kevin Tseng", "CUHK Business School (Hong Kong)"),
    (154, 154, "University of Illinois at Urbana-Champaign", "Laura W Wang", "Gies College of Business"),
    (155, 155, "Singapore Management University", "Liandong Zhang", "Lee Kong Chian School of Business"),
    (156, 156, "National University of Singapore (NUS)", "Luo Zuo", "NUS Business School"),
    (157, 157, "University of Pennsylvania", "Luzi Hail", "The Wharton School"),
    (158, 158, "University of Missouri at Columbia", "Mahfuz Chy", "Robert J. Trulaske, Sr. College of Business"),
    (159, 159, "University of North Carolina at Chapel Hill", "Mark Lang", "Kenan-Flagler Business School"),
    (160, 160, "Boston College", "Mark T Bradshaw", "Carroll School of Management"),
    (161, 161, "BI Norwegian Business School", "Marleen Willekens", "School of Management"),
    (162, 162, "Stanford University", "Mary E Barth", "Graduate School of Business"),
    (163, 163, "Massachusetts Institute of Technology (MIT)", "Matthew A Phillips", "Sloan School of Management"),
    (164, 164, "Emory University", "Matthew R Lyle", "Goizueta Business School"),
    (165, 165, "Texas A&M University at College Station", "Matthew S Ege", "Mays Business School"),
    (166, 166, "University of Maryland at College Park", "Michael D Kimbrough", "Robert H. Smith School of Business"),
    (167, 167, "Michigan State University", "Michelle L Nessa", "The Eli Broad College of Business"),
    (168, 168, "University of Michigan at Ann Arbor", "Mihir N Mehta", "Ross School of Business"),
    (169, 169, "Hong Kong University of Science and Technology (HKUST)", "Mingyi Hung", "Business School"),
    (170, 170, "University of Pennsylvania", "Mirko S. Heinle", "The Wharton School"),
    (171, 171, "Michigan State University", "Musaib Ashraf", "The Eli Broad College of Business"),
    (172, 172, "National University of Singapore (NUS)", "Oliver Zhen Li", "NUS Business School"),
    (173, 173, "Shanghai Lixin University of Finance and Accounting", "Oliver Zhen Li", ""),
    (174, 174, "London School of Economics and Political Science (LSE)", "Oscar Timmermans", ""),
    (175, 175, "Cornell University", "P Eric Yeung", "SC Johnson College of Business, Johnson Graduate School of Management (Incl. Dyson and Nolan)"),
    (176, 176, "University of Southern California", "Patricia M Dechow", "Marshall School of Business (incl. Leventhal)"),
    (177, 177, "University of Notre Dame", "Peter D Easton", "Mendoza College of Business"),
    (178, 178, "Singapore Management University", "Qiang Cheng", "Lee Kong Chian School of Business"),
    (179, 179, "Fudan University", "Qinlin Zhong", "School of Management"),
    (180, 180, "Duke University", "Rahul Vashishtha", "The Fuqua School of Business"),
    (181, 181, "Bentley University", "Rani Hoitash", "McCallum School of Business"),
    (182, 182, "Yale University", "Raphael Duguay", "School of Management"),
    (183, 183, "Singapore Management University", "Rencheng Wang", "Lee Kong Chian School of Business"),
    (184, 184, "University of Alabama at Tuscaloosa", "Richard C Hatfield", "Culverhouse College of Business"),
    (185, 185, "Pennsylvania State University at State College (Penn State)", "Richard D Mergenthaler", "Smeal College of Business"),
    (186, 186, "University of North Carolina at Chapel Hill", "Robert M Bushman", "Kenan-Flagler Business School"),
    (187, 187, "University of Texas at Austin", "Sara Toynbee", "McCombs School of Business"),
    (188, 188, "San Diego State University", "Shira Cohen", "College of Business Administration / Fowler College of Business Administration"),
    (189, 189, "KU Leuven / Katholieke Universiteit Leuven", "Simon Dekeyser", "Faculty of Economics and Business"),
    (190, 190, "Florida State University", "Spencer Pierce", "College of Business"),
    (191, 191, "University of Texas at Dallas", "Stanimir Markov", "Naveen Jindal School of Management"),
    (192, 192, "University of Texas at Austin", "Steven J Kachelmeier", "McCombs School of Business"),
    (193, 193, "Northwestern University", "Sugata Roychowdhury", "Kellogg School of Management"),
    (194, 194, "Boston College", "Susan Shu", "Carroll School of Management"),
    (195, 195, "Emory University", "Teri Lombardi Yohn", "Goizueta Business School"),
    (196, 196, "University of Georgia", "Theodore E. Christensen", "Terry College of Business"),
    (197, 197, "University of Nebraska at Lincoln", "Thomas R Kubick", "College of Business Administration"),
    (198, 198, "University of Kentucky", "Tyler J Kleppe", "Gatton College of Business and Economics"),
    (199, 199, "University of Chicago", "Valeri V Nikolaev", "Booth School of Business"),
    (200, 200, "Columbia University", "Wei Cai", "Columbia Business School"),
)


WATCH_TARGETS: tuple[WatchTarget, ...] = tuple(
    WatchTarget(
        source_row_number=source_row_number,
        rank=rank,
        school=school,
        name=name,
        school_unit=school_unit,
        normalized_name=normalize_text(name),
        overlap_tokens=tokenize_for_overlap(school, school_unit),
    )
    for source_row_number, rank, school, name, school_unit in RAW_WATCH_TARGETS
)


def load_watch_targets() -> list[WatchTarget]:
    return list(WATCH_TARGETS)
